Yotam playg 37 support insert fix
smartFreshBear/RecipeGrabber pull request #103
Opened 2023-08-10 21:19 UTC by yotam-yakovw

New and improved branch for my ticket
Commits went down to 2 and only relevant files are commited

2023-08-11 13:11 UTC, smartFreshBear commented on main_flow/main_flow.py
> +    steamed_dict = stemmer.stemmify(table)
why did you change the stemmed to steamed? you added a typo upon us!

2023-08-11 13:49 UTC, smartFreshBear requested changes
last small comment to fix and I will approve (squash the this small fix to the main one!!)

2023-08-11 15:29 UTC, yotam-yakovw commented
GIT IS HARD!
so I fixed the typo and commited the changes, then squashed the commit to the previous so it won't show but to push I was forced to merge the remote branch(?)
Now there is a copy of the last commit and another merge commit? what is going on and what am I doing wrong??

2023-08-11 20:01 UTC, smartFreshBear commented
yes because!!!
you merged instead rebase right?  like I said many times in Playground we don't merge...
but no worries.
you can keep the merge commit. 
but the rest you have to squash together

2023-08-12 18:54 UTC, yotam-yakovw commented
But it didn't let me push without merging I'm so confused
Was I supposed to pull and then push? Wouldn't it change things back again?

2023-08-12 19:11 UTC, yotam-yakovw commented
So I looked it up online, apparently because the commits were already in the remote branch I need to force push to change commits and that let me get pass the merge requirement.
somehow the merge commit disappeared so that's a plus I guess :D

2023-08-13 12:53 UTC, smartFreshBear approved these changes
approved, please verify u can train the model & send request successfully before "rebase & merge"

2023-08-13 19:44 UTC, yotam-yakovw commented
After logging branch revert rebased on master, fixed conflicts and tested the app
Force pushed changes and hopefully ready to merge

2023-08-16 08:07 UTC, smartFreshBear approved these changes

2023-08-16 16:58 UTC, merged